version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - CatChen
  ignore:
  - dependency-name: http-proxy-middleware
    versions:
    - 1.1.1
    - 1.1.2
    - 1.2.0
    - 1.3.0
  - dependency-name: husky
    versions:
    - 5.1.0
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: versioned-storage
    versions:
    - 1.2.1
