version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - CatChen
    reviewers:
      - CatChen
    labels:
      - accept2ship

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    reviewers:
      - catchen
    assignees:
      - catchen
    labels:
      - accept2ship
