pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - '#approved-reviews-by>=1'
      - 'status-failure!=LGTM analysis: JavaScript'
      - status-success=continuous-integration/travis-ci/pr
      - status-success=codecov/patch
    actions:
      merge:
        method: squash
      delete_head_branch:
