language: node_js
install:
  - yarn install
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn flow
  - yarn test src/ui --coverage --collectCoverageFrom=src/ui/** && yarn codecov -C -F ui
  - yarn test src/api --coverage --collectCoverageFrom=src/api/** && yarn codecov -C -F api
  - yarn test --testPathIgnorePatterns="src/(ui|api)" --coverage && yarn codecov -C -F app
