language: node_js
install:
  - yarn install
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
  - yarn flow
  - yarn test --coverage
  - yarn run codecov
